apiVersion: scheduling.flexcluster.io/v1alpha1
kind: FlexScheduler
metadata:
  labels:
    app.kubernetes.io/name: flexscheduler
    app.kubernetes.io/instance: flexscheduler-sample
    app.kubernetes.io/part-of: flex-scheduler
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: flex-scheduler
  name: flexscheduler-sample
spec:
  # TODO(user): Add fields here
